name: spark_python_template
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2022.9.24
  - libffi=3.4.2
  - libsqlite=3.40.0
  - libzlib=1.2.13
  - ncurses=6.3
  - openssl=3.0.7
  - pip=22.3.1
  - python=3.11.0
  - readline=8.1.2
  - setuptools=65.5.1
  - tk=8.6.12
  - tzdata=2022f
  - wheel=0.38.4
  - xz=5.2.6
  - pip:
    - alabaster==1.0.0
    - argparse==1.4.0
    - asttokens==3.0.0
    - babel==2.17.0
    - beautifulsoup4==4.13.4
    - certifi==2025.1.31
    - cffi==1.17.1
    - charset-normalizer==3.4.1
    - citeproc-py==0.8.2
    - codecov==2.1.13
    - contourpy==1.3.2
    - coverage==7.8.0
    - cryptography==44.0.2
    - css-html-js-minify==2.5.5
    - cycler==0.12.1
    - decorator==5.2.1
    - doctr==1.9.0
    - docutils==0.21.2
    - duecredit==0.10.2
    - executing==2.2.0
    - flake8==7.2.0
    - fonttools==4.57.0
    - idna==3.10
    - imagesize==1.4.1
    - importlib-resources==6.5.2
    - iniconfig==2.1.0
    - ipython==9.1.0
    - ipython-pygments-lexers==1.1.1
    - jedi==0.19.2
    - jinja2==3.1.6
    - jsonpointer==3.0.0
    - kiwisolver==1.4.8
    - looseversion==1.3.0
    - lxml==5.3.2
    - markupsafe==3.0.2
    - matplotlib==3.10.1
    - matplotlib-inline==0.1.7
    - mccabe==0.7.0
    - numpy==2.2.4
    - numpydoc==1.8.0
    - packaging==25.0
    - parso==0.8.4
    - pexpect==4.9.0
    - pillow==11.2.1
    - pluggy==1.5.0
    - prompt-toolkit==3.0.51
    - ptyprocess==0.7.0
    - pure-eval==0.2.3
    - pycodestyle==2.13.0
    - pycparser==2.22
    - pyflakes==3.3.2
    - pygments==2.19.1
    - pyparsing==3.2.3
    - pytest==8.3.5
    - python-dateutil==2.9.0.post0
    - python-slugify==8.0.4
    - pyyaml==6.0.2
    - requests==2.32.3
    - roman-numerals-py==3.1.0
    - six==1.17.0
    - snowballstemmer==2.2.0
    - soupsieve==2.6
    - spark-python-template==0+untagged.7.g720a561.dirty
    - sphinx==8.2.3
    - sphinx-argparse==0.5.2
    - sphinx-copybutton==0.5.2
    - sphinx-design==0.6.1
    - sphinx-gallery==0.19.0
    - sphinx-jsonschema==1.19.1
    - sphinx-material==0.0.36
    - sphinx-rtd-theme==3.0.2
    - sphinx-tabs==3.4.7
    - sphinxcontrib-applehelp==2.0.0
    - sphinxcontrib-devhelp==2.0.0
    - sphinxcontrib-htmlhelp==2.1.0
    - sphinxcontrib-jquery==4.1
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==2.0.0
    - sphinxcontrib-serializinghtml==2.0.0
    - stack-data==0.6.3
    - tabulate==0.9.0
    - text-unidecode==1.3
    - traitlets==5.14.3
    - typing-extensions==4.13.2
    - unidecode==1.3.8
    - urllib3==2.4.0
    - wcwidth==0.2.13
