name: test code

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install -r requirements-dev.txt
    - name: Install spark_python_template
      run: |
        pip install ./
    # - name: Test code
    #   shell: bash -l {0}
    #   run: |
    #     pytest
    #     flake8
